FROM public.ecr.aws/docker/library/debian:trixie-slim AS package
ARG VERSION=master
RUN apt-get update && apt-get install -y --no-install-recommends unzip \
	&& rm -rf /var/lib/apt/lists/*
COPY installers/traccar-other-$VERSION.zip /tmp/traccar.zip
RUN unzip -qo /tmp/traccar.zip -d /traccar

FROM gcr.io/distroless/java25-debian13:latest
COPY --from=package /traccar /opt/traccar
WORKDIR /opt/traccar
ENTRYPOINT ["/usr/bin/java", "-XX:+ExitOnOutOfMemoryError", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=70", "-XX:+UseZGC", "-XX:+UseStringDeduplication", "-XX:+UseCompactObjectHeaders", "-Djava.net.preferIPv4Stack=true", "--enable-native-access=ALL-UNNAMED", "--sun-misc-unsafe-memory-access=allow"]
CMD ["-jar", "tracker-server.jar", "conf/traccar.xml"]
