name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        default: preview

jobs:
  docker:
    name: Build and push docker images
    if: ${{ github.event.inputs.version != 'preview' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: alpine
            platforms: linux/amd64,linux/arm64
          - os: debian
            platforms: linux/amd64,linux/arm64,linux/arm/v7
          - os: ubuntu
            platforms: linux/amd64,linux/arm64,linux/arm/v7
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifact from previous run
        run: |
          gh run download 16101836490 -n installers -D docker
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: |
            traccar/traccar
            ghcr.io/traccar/traccar
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},suffix=-${{ matrix.os }},value=v${{ github.event.inputs.version }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.os }},value=v${{ github.event.inputs.version }}
            type=semver,pattern={{major}},suffix=-${{ matrix.os }},value=v${{ github.event.inputs.version }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=v${{ github.event.inputs.version }},enable=${{ matrix.os == 'alpine' }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ github.event.inputs.version }},enable=${{ matrix.os == 'alpine' }}
            type=semver,pattern={{major}},value=v${{ github.event.inputs.version }},enable=${{ matrix.os == 'alpine' }}
            type=raw,value=latest,enable=${{ matrix.os == 'alpine' }}
            type=raw,value=${{ matrix.os }}
          labels: |
            org.opencontainers.image.version=${{ github.event.inputs.version }}
      - uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile.${{ matrix.os }}
          build-args: VERSION=${{ github.event.inputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platforms }}
          push: true
